# Generated by Django 3.2.3 on 2021-08-24 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date_created', models.DateField(default='2021-08-24')),
                ('content', models.TextField(blank=True)),
                ('deadline', models.DateField(default='2021-08-24')),
                ('category', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to='ToDo_List.category')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
