/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatclientinterface;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 * La classe implementa un interfaccia grafica da dove l'utente potrà scegliere il proprio nickname e 
 * la stanza dove si vorrà connettere.
 * @author utente_2
 */
public class ChoiseFrame extends javax.swing.JFrame {
    /**
     * Creates new form ChoiseFrame
     */
    public ChoiseFrame() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNickname = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxRooms = new javax.swing.JComboBox();
        jButtonNext = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListUsers = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jButtonNewRoom = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListUsersOff = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelNickname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNickname.setText("Nickname:");

        jTextFieldName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldName.setText("Luca Giusti");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Choose Room");
        jLabel2.setEnabled(false);

        jComboBoxRooms.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxRooms.setEnabled(false);

        jButtonNext.setText("NEXT");
        jButtonNext.setEnabled(false);
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jListUsers);

        jLabel3.setText("Online users");

        jButtonNewRoom.setText("New Room");
        jButtonNewRoom.setEnabled(false);
        jButtonNewRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewRoomActionPerformed(evt);
            }
        });

        jButtonOk.setText("OK");
        jButtonOk.setToolTipText("");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jLabel1.setText("Offline users");

        jScrollPane3.setViewportView(jListUsersOff);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonNewRoom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxRooms, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOk)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButtonNewRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Comunica al server la stanza selezionata dall'utente e immette l'utente in quest'ultima.
     * @param evt Evento generato al cliccare del button "next".
     */
    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
       
            String msg="ATR"+jComboBoxRooms.getSelectedItem()+"⧫"+ChatClientInterface.nClient;
            ChatClientInterface.pw.println(msg);    
            this.setVisible(false);
            ChatClientInterface.ChatFrame.setRoomName(""+jComboBoxRooms.getSelectedItem());
            ChatClientInterface.ChatFrame.setVisible(true);
           
                        
    }//GEN-LAST:event_jButtonNextActionPerformed

    /**
     * Rimanda all'interfaccia grafica per creare una nuova stanza
     * @param evt Evento generato al cliccare del button "New Room"
     */
    private void jButtonNewRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewRoomActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ChatClientInterface.createRoomFrame.setVisible(true);
    }//GEN-LAST:event_jButtonNewRoomActionPerformed

    /**
     * Comunica al server il nickname scelto dall'utente.
     * @param evt Evento generato al cliccare del button "Ok".
     */
    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // TODO add your handling code here:
        if(!ChatClientInterface.UsersNames.contains(jTextFieldName.getText()) && !ChatClientInterface.UsersNamesOff.contains(jTextFieldName.getText())){
            ChatClientInterface.name=jTextFieldName.getText();
            String msg="IUN"+ChatClientInterface.name+"⧫"+ChatClientInterface.nClient;
            ChatClientInterface.pw.println(msg);
            jButtonOk.setEnabled(false);
            jLabelNickname.setEnabled(false);
            jTextFieldName.setEnabled(false);
            jLabel2.setEnabled(true);
            jComboBoxRooms.setEnabled(true);
            jButtonNext.setEnabled(true);
            jButtonNewRoom.setEnabled(true);
            
        }
        else{
            JOptionPane.showMessageDialog(null,"Nickename already exists, choose another one","ERRORE",JOptionPane.ERROR_MESSAGE);
        }                  
        
    }//GEN-LAST:event_jButtonOkActionPerformed

    /**
     * Comunica al server che l'utente si è scollegato dalla chat
     * @param evt Evento generato al cliccare della X della finestra
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        ChatClientInterface.sendToServer("RFL"+ChatClientInterface.nClient);       
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoiseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoiseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoiseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoiseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new ChoiseFrame().setVisible(true);
            }
        });
    }
    
    /**
     * Inizializza la comboBox con i nomi delle stanze presenti sul server
     */
    public void initializeRoomsComboBox(){
        String [] rooms;
        rooms=new String[ChatClientInterface.ChatRooms.size()];
        for(int i=0;i<rooms.length;i++)
            rooms[i]=(String) ChatClientInterface.ChatRooms.get(i);
        System.out.println(rooms);
        jComboBoxRooms.setModel(new javax.swing.DefaultComboBoxModel(rooms));
    }
    
    /**
     * Inizializza la lista degli utenti online 
     */
    
    public void initializeUsersList(){
        
        if(ChatClientInterface.UsersNames.size()!=0)
            jListUsers.setListData(ChatClientInterface.UsersNames.toArray());     
    }
    
    /**
     * inizializza la lista degli utenti offline
     */
    public void initializeUsersOffList(){
        
        if(ChatClientInterface.UsersNamesOff.size()!=0)
            jListUsersOff.setListData(ChatClientInterface.UsersNamesOff.toArray());     
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNewRoom;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JComboBox jComboBoxRooms;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelNickname;
    private javax.swing.JList jListUsers;
    private javax.swing.JList jListUsersOff;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
